sudo: required
dist: trusty

language: node_js
node_js: 8

services:
  - docker

os:
  - linux
  # - osx

install:
  - yarn global add lix haxe-travix
  - lix download
  - docker run -d --name fakesmtp -p 1025:25 -v /tmp/fakemail:/var/mail digiplant/fake-smtp

script:
  - travix node
